name: Sync template

on:
  workflow_call:
    inputs:
      templateRepo:
        required: true
        description: The template repository in the form of org/repo
        type: string

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout template repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.templateRepo }}
      - name: Install Mustache
        run: npm install -g mustache
      - name: Template generate
        run: |
          repo=${{ github.repository }})"
          jq --arg repo "$repo" '.repos[$repo].inputs' ./.gerp/config.json > inputs.json
          for f in $(find ./template -type f); do
            outpath=generated/${f#./*/}
            mkdir -p $(dirname $outpath) && touch $outpath
            mustache inputs.json $f > $outpath
            echo generated $outpath
          done
