name: "Template dispatch"

on:
  workflow_call:
    repos:
      description: "Repositories in the form of [org/repo, org2/repo]"
      required: true
      type: string
  workflow_dispatch:
    repos:
      description: "Repositories in the form of [org/repo, org2/repo]"
      required: true
      type: string

jobs:
  dispatch:
    strategy:
      matrix:
        repo: ${{ inputs.repos }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Trigger update
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: ${{ matrix.repo }},
              workflow_id: 'test.yml',
              ref: 'main',
            })
