name: Template dispatch

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setVariables.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: setVariables
        run: |
          repos=$(jq '.repos | keys' -c .gerp/config.json)
          echo "::set-output name=matrix::$repos"
  dispatch:
    permissions: write-all # todo investigate specifically which one is needed
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - name: Trigger update
        uses: actions/github-script@v6
        with:
          script: |
            const [owner, repo] = '${{ matrix.repo }}'.split('/');
            github.rest.actions.createWorkflowDispatch({
              owner: owner,
              repo: repo,
              workflow_id: 'sync_template.yaml',
              ref: 'main',
              inputs: {
                templateRepo: '${{ github.repository }}'
              }
            });
