name: "Template dispatch"

on:
  workflow_call:
    inputs:
      repos:
        description: 'Repositories in JSON form like ["org/repo", "org2/repo"]'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      repos:
        description: 'Repositories in JSON form like ["org/repo", "org2/repo"]'
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setVariables.outputs.repos }}
    steps:
      - id: setVariables
        run: |
          echo "::set-output name=repos::$repos"
        env:
          repos: ${{ inputs.repos }}
  dispatch:
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        repo: ${{ fromJson(needs.setup.outputs.repos) }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Trigger update
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: ${{ matrix.repo }},
              workflow_id: 'test.yml',
              ref: 'main',
            })
